version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  pre-release-check:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.0
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest --junitxml=tests/reports/junit.xml --html=tests/reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: tests/reports
